[package]
name = "php-rs-compiler"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
php-rs-lexer = { path = "../php-rs-lexer" }
php-rs-parser = { path = "../php-rs-parser" }

[dev-dependencies]
